[package]
name = "banana-leclerc"
version = "0.1.0"
edition = "2024"
description = "Team A push-back entry"

[package.metadata.v5]
upload-strategy = "differential"
compress = true

[profile.release]
lto = true
opt-level = 3

[features]
record = []

[dependencies]
autons = "0.2.0"
vex-sdk = "0.28.0"
vexide = { version = "0.8.0", features = ["full", "vex-sdk-vexcode", "vex-sdk-mock"] }
bincode = { version = "2.0.1", default-features = false, features = ["std", "alloc", "derive"] }
ozton = "0.2.0"
ozton-record = "0.2.0"
async-trait = "0.1.89"

[patch.crates-io]
ozton = { path = "../ozton/packages/ozton" }
ozton-record = { path = "../ozton/packages/ozton-record" }
