[package]
name = "banana-leclerc"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
opt-level = 3
# codegen-units = 1
# strip = true

[package.metadata.v5]
upload-strategy = "monolith"
slot = 2
icon = "cool-x"
compress = true

[features]
record = []

[dependencies]
autons = "0.2.0"
bincode = { version = "2.0.1", default-features = false, features = ["alloc", "derive"] }
vex-sdk = "0.28.0"
vexide = { version = "0.8.0", features = ["full", "vex-sdk-vexcode", "vex-sdk-mock"] }
