[package]
name = "recorder"
version = "0.1.0"
edition = "2024"
description = "Team A push-back entry"

[package.metadata.v5]
upload-strategy = "differential"
compress = true
slot = 2
icon = "code-file"

[profile.release]
lto = true
opt-level = 3

[features]
record = []

[dependencies]
autons = "0.2.0"
vex-sdk = "0.28.0"

[dependencies.bincode]
version = "2.0.1"
default-features = false
features = [
    "alloc",
    "derive",
]

[dependencies.vexide]
version = "0.8.0"
features = [
    "full",
    "vex-sdk-vexcode",
    "vex-sdk-mock",
]
